#define CONFIG_SYSCLK_16MHZ 1
#define CONFIG_VOLTAGE_3_3V 1
#define CONFIG_DRIVER_GPIO 1
#define CONFIG_DRIVER_RCC 1
#define CONFIG_DRIVER_UART 1
#define CONFIG_UART_BAUD_RATE 115200
#define CONFIG_TEST_UART 1
