#ifndef _ERRORS_H_
#define _ERRORS_H_

typedef enum error {
    SUCCESS = 0,
    VOLTAGE_NOT_SUPPORTED = 1,
    SYSCLK_FREQ_NOT_SUPPORTED,
    INCLK_FREQ_NOT_SUPPORTED,
    I2C_FREQ_NOT_SUPPORTED,
    I2C_APB1_FREQ_NOT_SUPPORTED,
    I2C_BUSY,
} error_t;

#endif
